### ISSUE TITLE
ClientPinAuthBlockPinRetriesTest: "The correct PIN is not blocked when auth is blocked."

### ISSUE THREAD

**Issue by mesink** [google/CTAP2-test-tool#130]
Hi all, I have a device that is failing this test and I'm trying to understand what it's doing/what the error means.

It seems like the test attempts 3 consecutive bad pin authentications (causing auth to be blocked) and then attempts a successful PIN and expects it to be rejected. However, from the language in the spec, it appears that the token is expected to accept this PIN. Intuitively the spec doesn't make sense here so I'm try `Authenticator performs following operations upon receiving the request:

    * Authenticator performs following operations upon receiving the request:
      * If Authenticator does not receive mandatory parameters for this command, it returns CTAP2_ERR_MISSING_PARAMETER error.
      * If the retries counter is 0, return CTAP2_ERR_PIN_BLOCKED error.
      * Authenticator generates "sharedSecret": SHA-256((abG).x) using private key of authenticatorKeyAgreementKey, "a" and public key of platformKeyAgreementKey, "bG".
        * SHA-256 is done over only "x" curve point of "abG"
      * Authenticator decrements the retries counter by 1.
      * Authenticator decrypts pinHashEnc and verifies against its internal stored LEFT(SHA-256(curPin), 16).
        * If a mismatch is detected, the authenticator performs the following operations:
          * Authenticator generates a new "authenticatorKeyAgreementKey".
            * Generate a new ECDH P-256 key pair called "authenticatorKeyAgreementKey" denoted by (a, aG), where "a" denotes the private key and "aG" denotes the public key.
          * Authenticator returns errors according to following conditions:
            * If the retries counter is 0, return CTAP2_ERR_PIN_BLOCKED error.
            * If the authenticator sees 3 consecutive mismatches, it returns CTAP2_ERR_PIN_AUTH_BLOCKED, indicating that power cycling is needed for further operations. This is done so that malware running on the platform should not be able to block the device without user interaction.
            * Else return CTAP2_ERR_PIN_INVALID error.
        * Authenticator sets the retries counter to 8.
        * Authenticator returns encrypted pinToken using "sharedSecret": AES256-CBC(sharedSecret, IV=0, pinToken).
          * pinToken should be a multiple of 16 bytes (AES block length) without any padding or IV. There is no PKCS #7 padding used in this scheme.

According to this, CTAP2_ERR_PIN_AUTH_BLOCKED is only ever returned on a bad PIN

**Comment by kaczmarczyck** [comment]
For me this is the key:

> power cycling is needed for further operations

If you accept correct PINs at this point, you can either brute force as many bad PINs as you like, or reduce the counter to 0 without power cycling. So you shouldn't perform a PIN check after 3 bad attempts.

I agree that if you read the specification like pseudocode, you wouldn't jump into this if:

> If a mismatch is detected

But unfortunately, it doesn't have these pseudocode like properties, even though it looks like it. That is my understanding. Does that help?

**Comment by ve7jtb** [comment]
Yes after three bad pin attempts the authenticator needs to stop accepting pin retries until after a power cycle.  

I will blame Jeff for that wording.

**Comment by mesink** [comment]
That helps clear things up a bit and that interpretation is also the more sensible one. Thanks!
