### ISSUE TITLE
make_credential_relying_party_entity: Remove icon check

### ISSUE THREAD

**Issue by robin-nitrokey** [google/CTAP2-test-tool#132]
The `make_credential_relying_party_entity` check requires that the authenticator supports the `icon` field in `PublicKeyCredentialRpEntity`.  This field has been removed in https://github.com/w3c/webauthn/pull/1337 so I think it should also be removed from the test suite.

**Comment by kaczmarczyck** [comment]
CTAP 2.2 mentions this change:

> NOTE: [[WebAuthn-2]](https://fidoalliance.org/specs/fido-v2.2-rd-20230321/fido-client-to-authenticator-protocol-v2.2-rd-20230321.html#biblio-webauthn-2) has removed the optional icon member. Authenticators MUST NOT error if the icon member is present, they MAY not store this value.

See the CTAP 2.2 draft: https://fidoalliance.org/specs/fido-v2.2-rd-20230321/fido-client-to-authenticator-protocol-v2.2-rd-20230321.html

Therefore I suggest to leave the test in place?

**Comment by robin-nitrokey** [comment]
I see, thanks for the info!  Feel free to close this issue.
