### ISSUE TITLE
Test item MakeCredentialExcludeListDepth

### ISSUE THREAD

**Issue by nuno0529** [google/CTAP2-test-tool#87]
test item:　**MakeCredentialExcludeListDepth**

    {
      "description": "Tests nested CBOR in the exclude list of MakeCredential.",
      "error_message": "Maximum CBOR nesting depth exceeded with array in credential descriptor transport list item in make credential command for key 5.",
      "id": "make_credential_exclude_list_depth",
      "observations": [
        "A prompt was sent unexpectedly.",
        "Expected error code `CTAP2_ERR_INVALID_CBOR`, got `CTAP2_OK`."
      ],
      "result": "fail",
      "tags": []
    },

It should be allowed for authenticator to support more than 5  
https://fidoalliance.org/specs/fido2/fido-client-to-authenticator-protocol-v2.1-rd-20191217.html#message-encoding
> Authenticators MUST support at least 4 levels of CBOR nesting.

Thanks for providing this tool !!
==

**Comment by kaczmarczyck** [comment]
Hmm, I swear I read that authenticators must only accept nesting depth 4... ;)

Thanks for reporting!

**Comment by nuno0529** [comment]
Thanks!
I guess this is due to the following and confusing sentence 
> Clients, platforms, and servers MUST NOT use more than 4 levels of CBOR nesting

**Comment by kaczmarczyck** [comment]
Ah, might have been that. But the other quote is pretty clear, so you are correct.
